In [8]:
import numpy as np

# 1장 벡터, 행렬, 행렬식

## 1.1 벡터와 공간

### 벡터(vector) : 수의 나열

In [9]:
np.array([2, 5]), np.array([6, 3, 3]), np.array([2.9, -0.3, 1/7, 42])

(array([2, 5]),
 array([6, 3, 3]),
 array([ 2.9       , -0.3       ,  0.14285714, 42.        ]))

### 벡터의 덧셈과 정수배

In [11]:
x = np.array([2, 9, 4])
y = np.array([7, 5, 3])
print(x + y)
print(3 * x)

[ 9 14  7]
[ 6 27 12]


### 벡터의 성질

In [35]:
c = 2
d = 3
print((c * d) * x)
print(c * (d * x))
print()
print(1 * x)
print(x)
print()
print(x + y)
print(y + x)
print()
z = np.array([10,20,30])
print((x + y) + z)
print(x + (y + z))
print()
print(x + np.array([0,0,0]))
print(x)
print()
print(x + (-x))
print()
print(c * (x + y))
print(c * x + c * y)
print()
print((c + d) * x)
print(c * x + d * x)

[12 54 24]
[12 54 24]

[2 9 4]
[2 9 4]

[ 9 14  7]
[ 9 14  7]

[19 34 37]
[19 34 37]

[2 9 4]
[2 9 4]

[0 0 0]

[18 28 14]
[18 28 14]

[10 45 20]
[10 45 20]


### 선형 공간(linear space) : 좌표와 방향 없이 벡터를 덧셈과 정수배로 표현하는 공간

### 기저(basis) : 선형 공간에서 기준이 되는 한 쌍의 벡터

$v = 3e_{1} + 2e_{2}$ 식에서 기저는 (e1, e2)를 의미하고 e1, e2를 기저 벡터라고 부름

### 벡터의 조합을 기저라 부르는 것은 기저가 되기 위한 조건은 다음 2가지를 만족시켰을 때 뿐이다.

1. 어떤 벡터라도 $v = x_{1}e_{1} + x_{2}e_{2} + ... + x_{n}x_{n}$ 의 형태로 나타낼 수 있다.  
2. 나타내는 방법은 오직 한 가지 뿐이다.  

### 차원 = 기저 베거의 개수 = 좌표의 성분수

## 1.2 행렬과 사상

행렬 : 수를 직사각형 형태로 나열한 것  
정방 행렬 : 행의 수와 열의 수가 같은 행렬 

$ A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} 
\end{pmatrix}$

### 행렬의 덧셈

In [36]:
A = np.array([[2, 9, 4], 
              [7, 5, 3]])
B = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(A + B)

[[ 3 11  7]
 [11 10  9]]


### 행렬의 정수배

In [37]:
print(3 * A)

[[ 6 27 12]
 [21 15  9]]


In [38]:
print(-A)
print(-1 * A)
print()
print(A - B)
print(A + (-B))
print()
print(2 * A + 3 * B)
print((2 * A) + (3 * B))

[[-2 -9 -4]
 [-7 -5 -3]]
[[-2 -9 -4]
 [-7 -5 -3]]

[[ 1  7  1]
 [ 3  0 -3]]
[[ 1  7  1]
 [ 3  0 -3]]

[[ 7 24 17]
 [26 25 24]]
[[ 7 24 17]
 [26 25 24]]


### 행렬의 곱셈

$ \begin{pmatrix} 
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{pmatrix}
\begin{pmatrix}
x_{1}
x_{2}
\end{pmatrix}
=
\begin{pmatrix}
a_{11}x_{1} + a_{12}x_{2} \\
a_{21}x_{1} + a_{22}x_{2}
\end{pmatrix} $

## 행렬은 사상(map)이다. : 행렬은 특정 벡터나 행렬을 이동시킬 수 있다.

n차원 벡터 x에 m x n 행렬 A를 곱하면 m차원 벡터 y= Ax를 얻을 수 있다.

In [41]:
x = np.array([3, 7])
A = np.array([[4, 9],
              [1, 11],
              [5, 6]])
y = np.dot(A, x)
print(y)

[75 80 57]


### 행렬의 곱 = 사상의 합성

In [54]:
A = np.array([[2, 9],
             [4, 7]])
B = np.array([[5, 3],
              [6, 8]])
C = np.array([[10, 20],
             [30, 40]])
x = np.array([3, 1])


print((10*A)*x)
print(c*(A*10))
print(A*(c*x),'\n')

print((A + B)*x)
print(A*x + B*x, '\n')

print(A + B)
print(B + A, '\n')

print((A + B) + C)
print(A + (B + C), '\n')

print((2 + 3)*A)
print(2*A + 3*A, '\n')

print((2*3)*A)
print(2*(3*A), '\n')

print(np.dot(A, (B + C)))
print(np.dot(A, B) + np.dot(A, C), '\n')

print(np.dot((A + B), C))
print(np.dot(A, C) + np.dot(B, C), '\n')

print(np.dot((10*A), B))
print(10*np.dot(A, B))
print(np.dot(A, (10*B)))

[[ 60  90]
 [120  70]]
[[ 40 180]
 [ 80 140]]
[[12 18]
 [24 14]] 

[[21 12]
 [30 15]]
[[21 12]
 [30 15]] 

[[ 7 12]
 [10 15]]
[[ 7 12]
 [10 15]] 

[[17 32]
 [40 55]]
[[17 32]
 [40 55]] 

[[10 45]
 [20 35]]
[[10 45]
 [20 35]] 

[[12 54]
 [24 42]]
[[12 54]
 [24 42]] 

[[354 478]
 [312 428]]
[[354 478]
 [312 428]] 

[[430 620]
 [550 800]]
[[430 620]
 [550 800]] 

[[640 780]
 [620 680]]
[[640 780]
 [620 680]]
[[640 780]
 [620 680]]


Test